
# This file is automatically generated, you probably don't want to edit this

.jmvrefs <- list(
    `brawstats`=list(
        `type`="software", 
        `author`="Watt, R. & Collins E.", 
        `year`=2019, 
        `title`="BrawStats: Psychology Research Simulation", 
        `publisher`="[Shiny App]", 
        `url`="https://doingpsychstats.wordpress.com/resources/brawstats-software"), 
    `book`=list(
        `type`="book", 
        `author`="Watt, R. & Collins E.", 
        `year`=2023, 
        `title`="Statistics for Psychology; 2nd Edition", 
        `publisher`="Sage"))
