
# This file is automatically generated, you probably don't want to edit this

BrawSimOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "BrawSimOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            DVname = "DV",
            DVtype = "Interval",
            DVmu = 0,
            DVsd = 1,
            DVskew = 0,
            DVkurt = 3,
            DVnlevs = 7,
            DViqr = 4,
            DVncats = 2,
            DVprops = "1,1",
            IVname = "IV",
            IVtype = "Interval",
            IVmu = 0,
            IVsd = 1,
            IVskew = 0,
            IVkurt = 3,
            IVnlevs = 7,
            IViqr = 4,
            IVncats = 2,
            IVprops = "1,1",
            IV2on = NULL,
            IV2name = "IV2",
            IV2type = "Interval",
            IV2mu = 0,
            IV2sd = 1,
            IV2skew = 0,
            IV2kurt = 3,
            IV2nlevs = 7,
            IV2iqr = 4,
            IV2ncats = 2,
            IV2props = "1,1",
            EffectSize1 = 0.3,
            EffectSize2 = 0.3,
            EffectSize3 = 0.3,
            EffectSize12 = 0.3,
            WorldOn = FALSE,
            WorldPDF = "Single",
            WorldRZ = NULL,
            Worldk = 0.3,
            WorldNullP = 0.5,
            SampleSize = 42,
            SampleSpread = "no",
            SampleGamma = 1.56,
            SampleMethod = "Random",
            SampleUsage1 = "Between",
            SampleUsage2 = "Between",
            Dependence = 0,
            Outliers = 0,
            Cheating = "None",
            CheatingAttempts = 5,
            shorthand = "no",
            Welch = "no",
            Transform = "None",
            multipleDoingNull = "no",
            showHypothesisBtn = NULL,
            makeSampleBtn = FALSE,
            numberSamples = 100,
            makeMultipleBtn = NULL,
            showSampleType = "Sample",
            showInferParam = "Basic",
            showMultipleParam = "Basic",
            whichShowMultiple = "all",
            exploreNPoints = 13,
            exploreMaxN = 250,
            exploreDoingNull = "no",
            exploreNscale = FALSE,
            numberExplores = 10,
            makeExploreBtn = NULL,
            typeExplore = "n",
            showExploreParam = "r",
            whichShowExplore = "all", ...) {

            super$initialize(
                package="BrawStats",
                name="BrawSim",
                requiresData=FALSE,
                ...)

            private$..DVname <- jmvcore::OptionString$new(
                "DVname",
                DVname,
                default="DV")
            private$..DVtype <- jmvcore::OptionList$new(
                "DVtype",
                DVtype,
                options=list(
                    "Interval",
                    "Ordinal",
                    "Categorical"),
                default="Interval")
            private$..DVmu <- jmvcore::OptionNumber$new(
                "DVmu",
                DVmu,
                default=0)
            private$..DVsd <- jmvcore::OptionNumber$new(
                "DVsd",
                DVsd,
                default=1)
            private$..DVskew <- jmvcore::OptionNumber$new(
                "DVskew",
                DVskew,
                default=0)
            private$..DVkurt <- jmvcore::OptionNumber$new(
                "DVkurt",
                DVkurt,
                default=3)
            private$..DVnlevs <- jmvcore::OptionNumber$new(
                "DVnlevs",
                DVnlevs,
                default=7)
            private$..DViqr <- jmvcore::OptionNumber$new(
                "DViqr",
                DViqr,
                default=4)
            private$..DVncats <- jmvcore::OptionNumber$new(
                "DVncats",
                DVncats,
                default=2)
            private$..DVprops <- jmvcore::OptionString$new(
                "DVprops",
                DVprops,
                default="1,1")
            private$..IVname <- jmvcore::OptionString$new(
                "IVname",
                IVname,
                default="IV")
            private$..IVtype <- jmvcore::OptionList$new(
                "IVtype",
                IVtype,
                options=list(
                    "Interval",
                    "Ordinal",
                    "Categorical"),
                default="Interval")
            private$..IVmu <- jmvcore::OptionNumber$new(
                "IVmu",
                IVmu,
                default=0)
            private$..IVsd <- jmvcore::OptionNumber$new(
                "IVsd",
                IVsd,
                default=1)
            private$..IVskew <- jmvcore::OptionNumber$new(
                "IVskew",
                IVskew,
                default=0)
            private$..IVkurt <- jmvcore::OptionNumber$new(
                "IVkurt",
                IVkurt,
                default=3)
            private$..IVnlevs <- jmvcore::OptionNumber$new(
                "IVnlevs",
                IVnlevs,
                default=7)
            private$..IViqr <- jmvcore::OptionNumber$new(
                "IViqr",
                IViqr,
                default=4)
            private$..IVncats <- jmvcore::OptionNumber$new(
                "IVncats",
                IVncats,
                default=2)
            private$..IVprops <- jmvcore::OptionString$new(
                "IVprops",
                IVprops,
                default="1,1")
            private$..IV2on <- jmvcore::OptionBool$new(
                "IV2on",
                IV2on)
            private$..IV2name <- jmvcore::OptionString$new(
                "IV2name",
                IV2name,
                default="IV2")
            private$..IV2type <- jmvcore::OptionList$new(
                "IV2type",
                IV2type,
                options=list(
                    "Interval",
                    "Ordinal",
                    "Categorical"),
                default="Interval")
            private$..IV2mu <- jmvcore::OptionNumber$new(
                "IV2mu",
                IV2mu,
                default=0)
            private$..IV2sd <- jmvcore::OptionNumber$new(
                "IV2sd",
                IV2sd,
                default=1)
            private$..IV2skew <- jmvcore::OptionNumber$new(
                "IV2skew",
                IV2skew,
                default=0)
            private$..IV2kurt <- jmvcore::OptionNumber$new(
                "IV2kurt",
                IV2kurt,
                default=3)
            private$..IV2nlevs <- jmvcore::OptionNumber$new(
                "IV2nlevs",
                IV2nlevs,
                default=7)
            private$..IV2iqr <- jmvcore::OptionNumber$new(
                "IV2iqr",
                IV2iqr,
                default=4)
            private$..IV2ncats <- jmvcore::OptionNumber$new(
                "IV2ncats",
                IV2ncats,
                default=2)
            private$..IV2props <- jmvcore::OptionString$new(
                "IV2props",
                IV2props,
                default="1,1")
            private$..EffectSize1 <- jmvcore::OptionNumber$new(
                "EffectSize1",
                EffectSize1,
                default=0.3)
            private$..EffectSize2 <- jmvcore::OptionNumber$new(
                "EffectSize2",
                EffectSize2,
                default=0.3)
            private$..EffectSize3 <- jmvcore::OptionNumber$new(
                "EffectSize3",
                EffectSize3,
                default=0.3)
            private$..EffectSize12 <- jmvcore::OptionNumber$new(
                "EffectSize12",
                EffectSize12,
                default=0.3)
            private$..WorldOn <- jmvcore::OptionBool$new(
                "WorldOn",
                WorldOn,
                default=FALSE)
            private$..WorldPDF <- jmvcore::OptionList$new(
                "WorldPDF",
                WorldPDF,
                options=list(
                    "Single",
                    "Double",
                    "Uniform",
                    "Gauss",
                    "Exp"),
                default="Single")
            private$..WorldRZ <- jmvcore::OptionList$new(
                "WorldRZ",
                WorldRZ,
                options=list(
                    "r",
                    "z"))
            private$..Worldk <- jmvcore::OptionNumber$new(
                "Worldk",
                Worldk,
                default=0.3)
            private$..WorldNullP <- jmvcore::OptionNumber$new(
                "WorldNullP",
                WorldNullP,
                default=0.5)
            private$..SampleSize <- jmvcore::OptionNumber$new(
                "SampleSize",
                SampleSize,
                default=42)
            private$..SampleSpread <- jmvcore::OptionList$new(
                "SampleSpread",
                SampleSpread,
                options=list(
                    "no",
                    "yes"),
                default="no")
            private$..SampleGamma <- jmvcore::OptionNumber$new(
                "SampleGamma",
                SampleGamma,
                default=1.56)
            private$..SampleMethod <- jmvcore::OptionList$new(
                "SampleMethod",
                SampleMethod,
                options=list(
                    "Random",
                    "Stratified",
                    "Cluster",
                    "Convenience"),
                default="Random")
            private$..SampleUsage1 <- jmvcore::OptionList$new(
                "SampleUsage1",
                SampleUsage1,
                options=list(
                    "Between",
                    "Within"),
                default="Between")
            private$..SampleUsage2 <- jmvcore::OptionList$new(
                "SampleUsage2",
                SampleUsage2,
                options=list(
                    "Between",
                    "Within"),
                default="Between")
            private$..Dependence <- jmvcore::OptionNumber$new(
                "Dependence",
                Dependence,
                default=0)
            private$..Outliers <- jmvcore::OptionNumber$new(
                "Outliers",
                Outliers,
                default=0)
            private$..Cheating <- jmvcore::OptionList$new(
                "Cheating",
                Cheating,
                options=list(
                    "None",
                    "Grow",
                    "Prune",
                    "Replace",
                    "Retry"),
                default="None")
            private$..CheatingAttempts <- jmvcore::OptionNumber$new(
                "CheatingAttempts",
                CheatingAttempts,
                default=5)
            private$..shorthand <- jmvcore::OptionList$new(
                "shorthand",
                shorthand,
                options=list(
                    "no",
                    "yes"),
                default="no")
            private$..Welch <- jmvcore::OptionList$new(
                "Welch",
                Welch,
                options=list(
                    "no",
                    "yes"),
                default="no")
            private$..Transform <- jmvcore::OptionList$new(
                "Transform",
                Transform,
                options=list(
                    "None",
                    "Log",
                    "Exp"),
                default="None")
            private$..multipleDoingNull <- jmvcore::OptionList$new(
                "multipleDoingNull",
                multipleDoingNull,
                options=list(
                    "no",
                    "yes"),
                default="no")
            private$..showHypothesisBtn <- jmvcore::OptionAction$new(
                "showHypothesisBtn",
                showHypothesisBtn)
            private$..makeSampleBtn <- jmvcore::OptionAction$new(
                "makeSampleBtn",
                makeSampleBtn,
                default=FALSE)
            private$..numberSamples <- jmvcore::OptionNumber$new(
                "numberSamples",
                numberSamples,
                default=100)
            private$..makeMultipleBtn <- jmvcore::OptionAction$new(
                "makeMultipleBtn",
                makeMultipleBtn)
            private$..showSampleType <- jmvcore::OptionList$new(
                "showSampleType",
                showSampleType,
                options=list(
                    "Sample",
                    "Describe",
                    "Infer"),
                default="Sample")
            private$..showInferParam <- jmvcore::OptionList$new(
                "showInferParam",
                showInferParam,
                options=list(
                    "Basic",
                    "2D",
                    "r",
                    "p",
                    "w",
                    "n",
                    "rp",
                    "wp",
                    "nw"),
                default="Basic")
            private$..showMultipleParam <- jmvcore::OptionList$new(
                "showMultipleParam",
                showMultipleParam,
                options=list(
                    "Basic",
                    "2D",
                    "r",
                    "p",
                    "w",
                    "n",
                    "rp",
                    "wp",
                    "nw",
                    "NHST",
                    "FDR",
                    "FMR"),
                default="Basic")
            private$..whichShowMultiple <- jmvcore::OptionList$new(
                "whichShowMultiple",
                whichShowMultiple,
                options=list(
                    "direct",
                    "unique",
                    "total",
                    "all"),
                default="all")
            private$..exploreNPoints <- jmvcore::OptionNumber$new(
                "exploreNPoints",
                exploreNPoints,
                default=13)
            private$..exploreMaxN <- jmvcore::OptionNumber$new(
                "exploreMaxN",
                exploreMaxN,
                default=250)
            private$..exploreDoingNull <- jmvcore::OptionList$new(
                "exploreDoingNull",
                exploreDoingNull,
                options=list(
                    "no",
                    "yes"),
                default="no")
            private$..exploreNscale <- jmvcore::OptionBool$new(
                "exploreNscale",
                exploreNscale,
                default=FALSE)
            private$..numberExplores <- jmvcore::OptionNumber$new(
                "numberExplores",
                numberExplores,
                default=10)
            private$..makeExploreBtn <- jmvcore::OptionAction$new(
                "makeExploreBtn",
                makeExploreBtn)
            private$..typeExplore <- jmvcore::OptionList$new(
                "typeExplore",
                typeExplore,
                options=list(
                    "rIV",
                    "rIVIV2",
                    "n",
                    "Method",
                    "Usage",
                    "Dependence",
                    "Outliers",
                    "Cheating",
                    "CheatingAmount",
                    "Alpha",
                    "Transform",
                    "IVType",
                    "DVType",
                    "IVskew",
                    "IVkurtosis",
                    "IVprops",
                    "DVskew",
                    "DVkurtosis",
                    "DVprops",
                    "Heteroscedasticity"),
                default="n")
            private$..showExploreParam <- jmvcore::OptionList$new(
                "showExploreParam",
                showExploreParam,
                options=list(
                    "r",
                    "p",
                    "w",
                    "n",
                    "rp",
                    "wp",
                    "wn",
                    "p(sig)",
                    "NHST",
                    "FDR",
                    "FMR"),
                default="r")
            private$..whichShowExplore <- jmvcore::OptionList$new(
                "whichShowExplore",
                whichShowExplore,
                options=list(
                    "direct",
                    "unique",
                    "total",
                    "all"),
                default="all")

            self$.addOption(private$..DVname)
            self$.addOption(private$..DVtype)
            self$.addOption(private$..DVmu)
            self$.addOption(private$..DVsd)
            self$.addOption(private$..DVskew)
            self$.addOption(private$..DVkurt)
            self$.addOption(private$..DVnlevs)
            self$.addOption(private$..DViqr)
            self$.addOption(private$..DVncats)
            self$.addOption(private$..DVprops)
            self$.addOption(private$..IVname)
            self$.addOption(private$..IVtype)
            self$.addOption(private$..IVmu)
            self$.addOption(private$..IVsd)
            self$.addOption(private$..IVskew)
            self$.addOption(private$..IVkurt)
            self$.addOption(private$..IVnlevs)
            self$.addOption(private$..IViqr)
            self$.addOption(private$..IVncats)
            self$.addOption(private$..IVprops)
            self$.addOption(private$..IV2on)
            self$.addOption(private$..IV2name)
            self$.addOption(private$..IV2type)
            self$.addOption(private$..IV2mu)
            self$.addOption(private$..IV2sd)
            self$.addOption(private$..IV2skew)
            self$.addOption(private$..IV2kurt)
            self$.addOption(private$..IV2nlevs)
            self$.addOption(private$..IV2iqr)
            self$.addOption(private$..IV2ncats)
            self$.addOption(private$..IV2props)
            self$.addOption(private$..EffectSize1)
            self$.addOption(private$..EffectSize2)
            self$.addOption(private$..EffectSize3)
            self$.addOption(private$..EffectSize12)
            self$.addOption(private$..WorldOn)
            self$.addOption(private$..WorldPDF)
            self$.addOption(private$..WorldRZ)
            self$.addOption(private$..Worldk)
            self$.addOption(private$..WorldNullP)
            self$.addOption(private$..SampleSize)
            self$.addOption(private$..SampleSpread)
            self$.addOption(private$..SampleGamma)
            self$.addOption(private$..SampleMethod)
            self$.addOption(private$..SampleUsage1)
            self$.addOption(private$..SampleUsage2)
            self$.addOption(private$..Dependence)
            self$.addOption(private$..Outliers)
            self$.addOption(private$..Cheating)
            self$.addOption(private$..CheatingAttempts)
            self$.addOption(private$..shorthand)
            self$.addOption(private$..Welch)
            self$.addOption(private$..Transform)
            self$.addOption(private$..multipleDoingNull)
            self$.addOption(private$..showHypothesisBtn)
            self$.addOption(private$..makeSampleBtn)
            self$.addOption(private$..numberSamples)
            self$.addOption(private$..makeMultipleBtn)
            self$.addOption(private$..showSampleType)
            self$.addOption(private$..showInferParam)
            self$.addOption(private$..showMultipleParam)
            self$.addOption(private$..whichShowMultiple)
            self$.addOption(private$..exploreNPoints)
            self$.addOption(private$..exploreMaxN)
            self$.addOption(private$..exploreDoingNull)
            self$.addOption(private$..exploreNscale)
            self$.addOption(private$..numberExplores)
            self$.addOption(private$..makeExploreBtn)
            self$.addOption(private$..typeExplore)
            self$.addOption(private$..showExploreParam)
            self$.addOption(private$..whichShowExplore)
        }),
    active = list(
        DVname = function() private$..DVname$value,
        DVtype = function() private$..DVtype$value,
        DVmu = function() private$..DVmu$value,
        DVsd = function() private$..DVsd$value,
        DVskew = function() private$..DVskew$value,
        DVkurt = function() private$..DVkurt$value,
        DVnlevs = function() private$..DVnlevs$value,
        DViqr = function() private$..DViqr$value,
        DVncats = function() private$..DVncats$value,
        DVprops = function() private$..DVprops$value,
        IVname = function() private$..IVname$value,
        IVtype = function() private$..IVtype$value,
        IVmu = function() private$..IVmu$value,
        IVsd = function() private$..IVsd$value,
        IVskew = function() private$..IVskew$value,
        IVkurt = function() private$..IVkurt$value,
        IVnlevs = function() private$..IVnlevs$value,
        IViqr = function() private$..IViqr$value,
        IVncats = function() private$..IVncats$value,
        IVprops = function() private$..IVprops$value,
        IV2on = function() private$..IV2on$value,
        IV2name = function() private$..IV2name$value,
        IV2type = function() private$..IV2type$value,
        IV2mu = function() private$..IV2mu$value,
        IV2sd = function() private$..IV2sd$value,
        IV2skew = function() private$..IV2skew$value,
        IV2kurt = function() private$..IV2kurt$value,
        IV2nlevs = function() private$..IV2nlevs$value,
        IV2iqr = function() private$..IV2iqr$value,
        IV2ncats = function() private$..IV2ncats$value,
        IV2props = function() private$..IV2props$value,
        EffectSize1 = function() private$..EffectSize1$value,
        EffectSize2 = function() private$..EffectSize2$value,
        EffectSize3 = function() private$..EffectSize3$value,
        EffectSize12 = function() private$..EffectSize12$value,
        WorldOn = function() private$..WorldOn$value,
        WorldPDF = function() private$..WorldPDF$value,
        WorldRZ = function() private$..WorldRZ$value,
        Worldk = function() private$..Worldk$value,
        WorldNullP = function() private$..WorldNullP$value,
        SampleSize = function() private$..SampleSize$value,
        SampleSpread = function() private$..SampleSpread$value,
        SampleGamma = function() private$..SampleGamma$value,
        SampleMethod = function() private$..SampleMethod$value,
        SampleUsage1 = function() private$..SampleUsage1$value,
        SampleUsage2 = function() private$..SampleUsage2$value,
        Dependence = function() private$..Dependence$value,
        Outliers = function() private$..Outliers$value,
        Cheating = function() private$..Cheating$value,
        CheatingAttempts = function() private$..CheatingAttempts$value,
        shorthand = function() private$..shorthand$value,
        Welch = function() private$..Welch$value,
        Transform = function() private$..Transform$value,
        multipleDoingNull = function() private$..multipleDoingNull$value,
        showHypothesisBtn = function() private$..showHypothesisBtn$value,
        makeSampleBtn = function() private$..makeSampleBtn$value,
        numberSamples = function() private$..numberSamples$value,
        makeMultipleBtn = function() private$..makeMultipleBtn$value,
        showSampleType = function() private$..showSampleType$value,
        showInferParam = function() private$..showInferParam$value,
        showMultipleParam = function() private$..showMultipleParam$value,
        whichShowMultiple = function() private$..whichShowMultiple$value,
        exploreNPoints = function() private$..exploreNPoints$value,
        exploreMaxN = function() private$..exploreMaxN$value,
        exploreDoingNull = function() private$..exploreDoingNull$value,
        exploreNscale = function() private$..exploreNscale$value,
        numberExplores = function() private$..numberExplores$value,
        makeExploreBtn = function() private$..makeExploreBtn$value,
        typeExplore = function() private$..typeExplore$value,
        showExploreParam = function() private$..showExploreParam$value,
        whichShowExplore = function() private$..whichShowExplore$value),
    private = list(
        ..DVname = NA,
        ..DVtype = NA,
        ..DVmu = NA,
        ..DVsd = NA,
        ..DVskew = NA,
        ..DVkurt = NA,
        ..DVnlevs = NA,
        ..DViqr = NA,
        ..DVncats = NA,
        ..DVprops = NA,
        ..IVname = NA,
        ..IVtype = NA,
        ..IVmu = NA,
        ..IVsd = NA,
        ..IVskew = NA,
        ..IVkurt = NA,
        ..IVnlevs = NA,
        ..IViqr = NA,
        ..IVncats = NA,
        ..IVprops = NA,
        ..IV2on = NA,
        ..IV2name = NA,
        ..IV2type = NA,
        ..IV2mu = NA,
        ..IV2sd = NA,
        ..IV2skew = NA,
        ..IV2kurt = NA,
        ..IV2nlevs = NA,
        ..IV2iqr = NA,
        ..IV2ncats = NA,
        ..IV2props = NA,
        ..EffectSize1 = NA,
        ..EffectSize2 = NA,
        ..EffectSize3 = NA,
        ..EffectSize12 = NA,
        ..WorldOn = NA,
        ..WorldPDF = NA,
        ..WorldRZ = NA,
        ..Worldk = NA,
        ..WorldNullP = NA,
        ..SampleSize = NA,
        ..SampleSpread = NA,
        ..SampleGamma = NA,
        ..SampleMethod = NA,
        ..SampleUsage1 = NA,
        ..SampleUsage2 = NA,
        ..Dependence = NA,
        ..Outliers = NA,
        ..Cheating = NA,
        ..CheatingAttempts = NA,
        ..shorthand = NA,
        ..Welch = NA,
        ..Transform = NA,
        ..multipleDoingNull = NA,
        ..showHypothesisBtn = NA,
        ..makeSampleBtn = NA,
        ..numberSamples = NA,
        ..makeMultipleBtn = NA,
        ..showSampleType = NA,
        ..showInferParam = NA,
        ..showMultipleParam = NA,
        ..whichShowMultiple = NA,
        ..exploreNPoints = NA,
        ..exploreMaxN = NA,
        ..exploreDoingNull = NA,
        ..exploreNscale = NA,
        ..numberExplores = NA,
        ..makeExploreBtn = NA,
        ..typeExplore = NA,
        ..showExploreParam = NA,
        ..whichShowExplore = NA)
)

BrawSimResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "BrawSimResults",
    inherit = jmvcore::Group,
    active = list(
        graphPlot = function() private$.items[["graphPlot"]],
        reportPlot = function() private$.items[["reportPlot"]],
        debug = function() private$.items[["debug"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="BrawStats:Simulate Data",
                refs="brawstats book")
            self$add(jmvcore::Image$new(
                options=options,
                name="graphPlot",
                title=" ",
                width=600,
                height=360,
                visible=TRUE,
                renderFun=".plotGraph"))
            self$add(jmvcore::Image$new(
                options=options,
                name="reportPlot",
                title=" ",
                width=600,
                height=200,
                visible=TRUE,
                refs=list(
                    "brawstats",
                    "book"),
                renderFun=".plotReport"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="debug",
                visible=FALSE))}))

BrawSimBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "BrawSimBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "BrawStats",
                name = "BrawSim",
                version = c(1,0,0),
                options = options,
                results = BrawSimResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'na')
        }))

#' BrawStats:Simulate Data
#'
#' 
#' @param DVname .
#' @param DVtype .
#' @param DVmu .
#' @param DVsd .
#' @param DVskew .
#' @param DVkurt .
#' @param DVnlevs .
#' @param DViqr .
#' @param DVncats .
#' @param DVprops .
#' @param IVname .
#' @param IVtype .
#' @param IVmu .
#' @param IVsd .
#' @param IVskew .
#' @param IVkurt .
#' @param IVnlevs .
#' @param IViqr .
#' @param IVncats .
#' @param IVprops .
#' @param IV2on .
#' @param IV2name .
#' @param IV2type .
#' @param IV2mu .
#' @param IV2sd .
#' @param IV2skew .
#' @param IV2kurt .
#' @param IV2nlevs .
#' @param IV2iqr .
#' @param IV2ncats .
#' @param IV2props .
#' @param EffectSize1 .
#' @param EffectSize2 .
#' @param EffectSize3 .
#' @param EffectSize12 .
#' @param WorldOn .
#' @param WorldPDF .
#' @param WorldRZ .
#' @param Worldk .
#' @param WorldNullP .
#' @param SampleSize .
#' @param SampleSpread .
#' @param SampleGamma .
#' @param SampleMethod .
#' @param SampleUsage1 .
#' @param SampleUsage2 .
#' @param Dependence .
#' @param Outliers .
#' @param Cheating .
#' @param CheatingAttempts .
#' @param shorthand .
#' @param Welch .
#' @param Transform .
#' @param multipleDoingNull .
#' @param showHypothesisBtn .
#' @param makeSampleBtn .
#' @param numberSamples .
#' @param makeMultipleBtn .
#' @param showSampleType .
#' @param showInferParam .
#' @param showMultipleParam .
#' @param whichShowMultiple .
#' @param exploreNPoints .
#' @param exploreMaxN .
#' @param exploreDoingNull .
#' @param exploreNscale .
#' @param numberExplores .
#' @param makeExploreBtn .
#' @param typeExplore .
#' @param showExploreParam .
#' @param whichShowExplore .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$graphPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$reportPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$debug} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
BrawSim <- function(
    DVname = "DV",
    DVtype = "Interval",
    DVmu = 0,
    DVsd = 1,
    DVskew = 0,
    DVkurt = 3,
    DVnlevs = 7,
    DViqr = 4,
    DVncats = 2,
    DVprops = "1,1",
    IVname = "IV",
    IVtype = "Interval",
    IVmu = 0,
    IVsd = 1,
    IVskew = 0,
    IVkurt = 3,
    IVnlevs = 7,
    IViqr = 4,
    IVncats = 2,
    IVprops = "1,1",
    IV2on,
    IV2name = "IV2",
    IV2type = "Interval",
    IV2mu = 0,
    IV2sd = 1,
    IV2skew = 0,
    IV2kurt = 3,
    IV2nlevs = 7,
    IV2iqr = 4,
    IV2ncats = 2,
    IV2props = "1,1",
    EffectSize1 = 0.3,
    EffectSize2 = 0.3,
    EffectSize3 = 0.3,
    EffectSize12 = 0.3,
    WorldOn = FALSE,
    WorldPDF = "Single",
    WorldRZ,
    Worldk = 0.3,
    WorldNullP = 0.5,
    SampleSize = 42,
    SampleSpread = "no",
    SampleGamma = 1.56,
    SampleMethod = "Random",
    SampleUsage1 = "Between",
    SampleUsage2 = "Between",
    Dependence = 0,
    Outliers = 0,
    Cheating = "None",
    CheatingAttempts = 5,
    shorthand = "no",
    Welch = "no",
    Transform = "None",
    multipleDoingNull = "no",
    showHypothesisBtn,
    makeSampleBtn = FALSE,
    numberSamples = 100,
    makeMultipleBtn,
    showSampleType = "Sample",
    showInferParam = "Basic",
    showMultipleParam = "Basic",
    whichShowMultiple = "all",
    exploreNPoints = 13,
    exploreMaxN = 250,
    exploreDoingNull = "no",
    exploreNscale = FALSE,
    numberExplores = 10,
    makeExploreBtn,
    typeExplore = "n",
    showExploreParam = "r",
    whichShowExplore = "all") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("BrawSim requires jmvcore to be installed (restart may be required)")


    options <- BrawSimOptions$new(
        DVname = DVname,
        DVtype = DVtype,
        DVmu = DVmu,
        DVsd = DVsd,
        DVskew = DVskew,
        DVkurt = DVkurt,
        DVnlevs = DVnlevs,
        DViqr = DViqr,
        DVncats = DVncats,
        DVprops = DVprops,
        IVname = IVname,
        IVtype = IVtype,
        IVmu = IVmu,
        IVsd = IVsd,
        IVskew = IVskew,
        IVkurt = IVkurt,
        IVnlevs = IVnlevs,
        IViqr = IViqr,
        IVncats = IVncats,
        IVprops = IVprops,
        IV2on = IV2on,
        IV2name = IV2name,
        IV2type = IV2type,
        IV2mu = IV2mu,
        IV2sd = IV2sd,
        IV2skew = IV2skew,
        IV2kurt = IV2kurt,
        IV2nlevs = IV2nlevs,
        IV2iqr = IV2iqr,
        IV2ncats = IV2ncats,
        IV2props = IV2props,
        EffectSize1 = EffectSize1,
        EffectSize2 = EffectSize2,
        EffectSize3 = EffectSize3,
        EffectSize12 = EffectSize12,
        WorldOn = WorldOn,
        WorldPDF = WorldPDF,
        WorldRZ = WorldRZ,
        Worldk = Worldk,
        WorldNullP = WorldNullP,
        SampleSize = SampleSize,
        SampleSpread = SampleSpread,
        SampleGamma = SampleGamma,
        SampleMethod = SampleMethod,
        SampleUsage1 = SampleUsage1,
        SampleUsage2 = SampleUsage2,
        Dependence = Dependence,
        Outliers = Outliers,
        Cheating = Cheating,
        CheatingAttempts = CheatingAttempts,
        shorthand = shorthand,
        Welch = Welch,
        Transform = Transform,
        multipleDoingNull = multipleDoingNull,
        showHypothesisBtn = showHypothesisBtn,
        makeSampleBtn = makeSampleBtn,
        numberSamples = numberSamples,
        makeMultipleBtn = makeMultipleBtn,
        showSampleType = showSampleType,
        showInferParam = showInferParam,
        showMultipleParam = showMultipleParam,
        whichShowMultiple = whichShowMultiple,
        exploreNPoints = exploreNPoints,
        exploreMaxN = exploreMaxN,
        exploreDoingNull = exploreDoingNull,
        exploreNscale = exploreNscale,
        numberExplores = numberExplores,
        makeExploreBtn = makeExploreBtn,
        typeExplore = typeExplore,
        showExploreParam = showExploreParam,
        whichShowExplore = whichShowExplore)

    analysis <- BrawSimClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

