plotAxis<-function(showType,effect) {
  
  explicitLog<-FALSE
  
  logScale<-(is.element(showType,c("p","e1","e2")) && braw.env$pPlotScale=="log10") ||
    (is.element(showType,c("ws","wp")) && braw.env$wPlotScale=="log10") ||
    (is.element(showType,c("n","no")) && braw.env$nPlotScale=="log10") ||
    (is.element(showType,c("nw")))
  
  switch(braw.env$RZ,
         "r"={
           rlims<-c(-1,1)
           rslab<-braw.env$rsLabel 
           rplab<-braw.env$rpLabel 
           rticks<-seq(-1,1,0.5)
           rmins<-seq(-1,1,0.1)
         },
         "z"={    
           rlims<-c(-1,1)*braw.env$z_range
           rslab<-braw.env$zsLabel
           rplab<-braw.env$zpLabel
           rticks<-seq(-1.5,1.5,0.5)
           rmins<-seq(-1.5,1.5,0.1)
         }
  )
  plabel<-bquote(bold(p))
  polabel<-bquote(bold(p[o]))
  switch(braw.env$pPlotScale,
         "log10"={
           plim<-c(-4,0)
           pticks<-seq(-4,0,1)
           pmins<-log10(c(seq(1,10)/10000,seq(1,10)/1000,seq(1,10)/100,seq(1,10)/10))
           plines<-log10(c(0.05,0.01,0.005,0.001))
           if (explicitLog) {
             plabel<-bquote(bold(log['10'](p)))
             polabel<-bquote(bold(log['10'](p[o])))
           }
         },
         "linear"={
           plim<-c(braw.env$min_p, 1)
           pticks<-seq(0,1,0.2)
           pmins<-seq(0,1,0.1)
           plines<-c(0.05)
         }
         )
  wslabel<-bquote(bold(w[s]))
  wplabel<-bquote(bold(w[p]))
  switch (braw.env$wPlotScale,
          "log10"={
            wlim<-c(-2,0)
            wticks<-seq(-2,0,1)
            wmins<-log10(c(seq(1,10)/100,seq(1,10)/10))
            if (explicitLog) {
              wslabel<-bquote(bold(log['10'](w[s])))
              wplabel<-bquote(bold(log['10'](w[p])))
            }
            wlines<-log10(c(0.05,0.8))
          },
          "linear"={
            wlim<-c(0, 1)
            wticks<-seq(0,1,0.2)
            wmins<-seq(0,1,0.1)
            wlines<-c(0.05,0.8)
          }
  )
  nlabel<-bquote(bold(n))
  switch(braw.env$nPlotScale,
         "log10"={
           nlim<-log10(c(5,2000))
           nticks<-seq(1,3,1)
           nmins<-log10(c(seq(5,10),seq(1,10)*10,seq(1,10)*100))
           if (explicitLog) {
             nlabel<-bquote(bold(log['10'](n)))
           }
         },
         "linear"={
           nlim<-c(1, 50*5*1.1)
           nticks<-seq(0,250,50)
           nmins<-seq(0,250,10)
         }
  )
  
  use_cols<-c("#FFFFFF","#DDDDDD","#AAAAAA")
  ylines<-c()
  ymins<-c()
  yticks<-c()
  
  switch (showType,
          "rs"={
            ylim<-rlims
            yticks<-rticks
            ymins<-rmins
            ylabel<-rslab
            use_cols<-c(hsv(0.1,1,1),hsv(0.1+0.075,1,1),hsv(0.1+0.15,1,1))
            ylines<-c(0,effect$rIV)
          },
          "rp"={
            ylim<-rlims
            yticks<-rticks
            ymins<-rmins
            ylabel<-rplab
            use_cols<-c(hsv(0.1,1,1),hsv(0.1+0.075,1,1),hsv(0.1+0.15,1,1))
            ylines<-c(0)
          },
          "re"={
            ylim<-rlims
            yticks<-rticks
            ymins<-rmins
            ylabel<-bquote(bold(r[e]))
            use_cols<-c(hsv(0.1,1,1),hsv(0.1+0.075,1,1),hsv(0.1+0.15,1,1))
            ylines<-c(0)
          },
          "ro"={
            ylim<-rlims
            yticks<-rticks
            ymins<-rmins
            ylabel<-bquote(bold(r[o]))
            use_cols<-c(hsv(0.1,1,1),hsv(0.1+0.075,1,1),hsv(0.1+0.15,1,1))
            ylines<-c(0,effect$rIV)
          },
          "p"={
            ylim<-plim
            yticks<-pticks
            ymins<-pmins
            ylabel<-plabel
            ylines<-plines
            use_cols<-c(hsv(0,1,1),hsv(0+0.075,1,1),hsv(0+0.15,1,1))
          },
          "po"={
            ylim<-plim
            yticks<-pticks
            ymins<-pmins
            ylines<-plines
            ylabel<-polabel
            use_cols<-c(hsv(0,1,1),hsv(0+0.075,1,1),hsv(0+0.15,1,1))
          },
          "log(lrs)"={
            ylim<-c(0, braw.env$lrRange)
            ylabel<-bquote(log[e](lr[s]))
            use_cols<-c(hsv(0,1,1),hsv(0+0.075,1,1),hsv(0+0.15,1,1))
          },
          "log(lrd)"={
            ylim<-c(-braw.env$lrRange, braw.env$lrRange)
            ylabel<-bquote(log[e](lr[d]))
            use_cols<-c(hsv(0,1,1),hsv(0+0.075,1,1),hsv(0+0.15,1,1))
          },
          "e1d"={
            ylim<-c(-braw.env$lrRange, braw.env$lrRange)
            ylabel<-bquote(log[e](lr[d]))
            use_cols<-c(hsv(0,1,1),hsv(0+0.075,1,1),hsv(0+0.15,1,1))
          },
          "e2d"={
            ylim<-c(-braw.env$lrRange, braw.env$lrRange)
            ylabel<-bquote(log[e](lr[d]))
            use_cols<-c(hsv(0,1,1),hsv(0+0.075,1,1),hsv(0+0.15,1,1))
          },
          "ws"={
            ylim<-wlim
            yticks<-wticks
            ymins<-wmins
            ylabel<-wslabel
            ylines<-wlines
            use_cols<-c(hsv(0.65,1,1),hsv(0.65+0.075,1,1),hsv(0.65+0.15,1,1))
          },
          "nw"={
            ylim<-log10(c(5,2000))
            yticks<-seq(0,3,1)
            if (explicitLog)
              ylabel<-bquote(bold(log['10'](n[w=80])))
            else
              ylabel<-bquote(bold(n[w=80]))
            logScale<-TRUE
          },
          "n"={
            ylim<-nlim
            yticks<-nticks
            ymins<-nmins
            ylabel<-nlabel
          },
          "no"={
            ylim<-nlim
            yticks<-nticks
            ymins<-nmins
            if (explicitLog)
              ylabel<-bquote(bold(log['10'](no)))
            else
              ylabel<-bquote(bold(no))
          },
          "wp"={
            ylim<-wlim
            yticks<-wticks
            ymins<-log10(c(seq(1,10),seq(1,10)*10,seq(1,10)*100))
            ylabel<-wplabel
            ylines<-wlines
            use_cols<-c(hsv(0.65,1,1),hsv(0.65+0.075,1,1),hsv(0.65+0.15,1,1))
          },
          "ci1"={
            ylim<-rlims
            yticks<-rticks
            ymins<-rmins
            ylabel<-rslab
            use_cols<-c(hsv(0.1,1,1),hsv(0.1+0.075,1,1),hsv(0.1+0.15,1,1))
            ylines<-c(0,effect$rIV)
          },
          "ci2"={
            ylim<-rlims
            yticks<-rticks
            ymins<-rmins
            ylabel<-rslab
            use_cols<-c(hsv(0.1,1,1),hsv(0.1+0.075,1,1),hsv(0.1+0.15,1,1))
            ylines<-c(0,effect$rIV)
          },
          "e1"={
            ylim<-plim
            yticks<-pticks
            ymins<-pmins
            ylabel<-plabel
            ylines<-plines
            use_cols<-c(hsv(0,1,1),hsv(0+0.075,1,1),hsv(0+0.15,1,1))
          },
          "e2"={
            ylim<-plim
            yticks<-pticks
            ymins<-pmins
            ylabel<-plabel
            ylines<-plines
            use_cols<-c(hsv(0,1,1),hsv(0+0.075,1,1),hsv(0+0.15,1,1))
          },
          "Hits"={
            ylim<-c(0,1)
            ytick<-seq(0,1,0.2)
            ymins<-seq(0,1,0.1)
            ylabel<-"True Hits"
            use_cols<-braw.env$plotColours$fdr
          },
          "NHST"={
            ylim<-c(0,1)
            ytick<-seq(0,1,0.2)
            ymins<-seq(0,1,0.1)
            ylabel<-"Outcomes"
          },
          "p(sig)"={
            ylim<-c(0,1)
            ytick<-seq(0,1,0.2)
            ymins<-seq(0,1,0.1)
            ylabel<-"p(sig)"
            lines<-c(0.05,0.8)
            use_cols<-c(braw.env$plotColours$infer_sigC,
                        braw.env$plotColours$infer_nsigC,
                        braw.env$plotColours$infer_sigNull,
                        braw.env$plotColours$infer_nsigNull)
            
            },
          "Misses"={
            ylim<-c(0,1)
            ytick<-seq(0,1,0.2)
            ymins<-seq(0,1,0.1)
            ylabel<-"False Miss"
            use_cols<-braw.env$plotColours$fmr
          },
          "Lambda"={
            ylim<-c(-0.01,1.01)
            ytick<-seq(0,1,0.2)
            ymins<-seq(0,1,0.1)
            ylabel<-braw.env$Llabel
          },
          "k"={
            ylim<-c(-0.01,1.01)
            ytick<-seq(0,1,0.2)
            ymins<-seq(0,1,0.1)
            ylabel<-braw.env$Llabel
          },
          "pNull"={
            ylim<-c(-0.01,1.01)
            ytick<-seq(0,1,0.2)
            ymins<-seq(0,1,0.1)
            ylabel<-braw.env$Plabel
          },
          "PDF"={
            ylim<-c(0,1)
            ytick<-seq(0,1,0.2)
            ymins<-seq(0,1,0.1)
            ylabel<-"p(PDF)"
          },
          "S"={
            ylim<-c(min(result$Ss),max(result$Ss))
            ylabel<-"S"
            ytick<-seq(ceil(min(result$Ss)),ceil(max(result$Ss)),1)
          }
  )
  
  return(list(lim=ylim,ticks=yticks,label=ylabel,cols=use_cols,lines=ylines,logScale=logScale))
}
